import './globals.css'
import Footer from '@comp/footer'
import Nav from '@comp/nav'

import { modularScale } from 'polished'

const globStyle = {
  'font-size': modularScale(2)
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body style={globStyle}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
